name: OGC Validator Action
description: A GitHub Action to validate OGC API endpoints.
author: Geo Engine GmbH

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
    icon: check-square
    color: blue

# Define your inputs here.
inputs:
    # teamengine-port:
    #     description: Port on which TeamEngine will run
    #     default: '8080'
    service-url:
        description: URL of the OGC endpoint to validate
        required: true
        default: http://localhost:8484/
    ogc-api-common:
        description: If set, validate OGC API - Common
        default: false
    ogc-api-common-container-tag:
        description: Container tag to use for OGC API - Common validation
        default: '1.0-teamengine-6.0.0-RC2'
    ogc-api-common-ignore:
        description:
            Multi-line list of test identifiers to ignore for OGC API - Common
            validation
        default: ''
    ogc-api-processes:
        description: If set, validate OGC API - Processes
        default: false
    ogc-api-processes-container-tag:
        description: Container tag to use for OGC API - Processes 1.0 validation
        default: '1.3-teamengine-6.0.0-RC2'
    echoprocessid:
        description:
            The process identifier to run for OGC API - Processes validation
        default: echo
    ogc-api-processes-ignore:
        description:
            Multi-line list of test identifiers to ignore for OGC API -
            Processes validation
        default: ''
    ogc-api-features:
        description: If set, validate OGC API - Features
        default: false
    ogc-api-features-container-tag:
        description: Container tag to use for OGC API - Features 1.0 validation
        default: '1.9-teamengine-6.0.0-RC2'
    ogc-api-features-ignore:
        description:
            Multi-line list of test identifiers to ignore for OGC API - Features
            validation
        default: ''
    ogc-api-tiles:
        description: If set, validate OGC API - Tiles
        default: false
    ogc-api-tiles-container-tag:
        description: Container tag to use for OGC API - Tiles 1.0 validation
        default: '1.2-teamengine-6.0.0-RC2'
    ogc-api-tiles-ignore:
        description:
            Multi-line list of test identifiers to ignore for OGC API - Tiles
            validation
        default: ''

# Define your outputs here.
# outputs:

runs:
    using: node24
    main: dist/index.js
